font_size 18.0

font_family JetBrains Mono

hide_window_decorations yes
window_padding_width 5

scrollback_lines 5000

cursor_shape block
cursor_blink_interval 0.5

enable_audio_bell no
confirm_os_window_close 0

# Launch
map ctrl+t launch --type=overlay --cwd=current tmux
map ctrl+enter launch --type=overlay --cwd=current nvim .
map ctrl+e launch --type=overlay --cwd=current yazi
map ctrl+f launch --type=overlay --cwd=current freebuff 


# Clear
map ctrl+space send_text all clear\x0d

# Movements
map alt+h send_text all \x1b[1;5D
map alt+l send_text all \x1b[1;5C
map alt+j send_text all \x1b[1;5B
map alt+k send_text all \x1b[1;5A
map alt+shift+l send_text all \x05
map alt+shift+h send_text all \x01

# Scroll
map alt+k scroll_page_up
map alt+j scroll_page_down

# Zoom
map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+r change_font_size all 0
