monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_input.*"
      }
    ]
    actions = {
      update-properties = {
        node.description = "Fixed Microphone"
        default.configured-node-volume = 0.65
      }
    }
  }
]
